// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhPR95yHorSq5cmo6yl4Yt3dnmjvPe48',
    appId: '1:588339996687:web:36aa8e91a120d9ab6a9b7a',
    messagingSenderId: '588339996687',
    projectId: 'admin-e5d62',
    authDomain: 'admin-e5d62.firebaseapp.com',
    storageBucket: 'admin-e5d62.firebasestorage.app',
    measurementId: 'G-MXH45BPP2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwBWcXmncgQziUq5NbTPH2ymGP1ce4b_0',
    appId: '1:588339996687:android:d74d8e353bafddac6a9b7a',
    messagingSenderId: '588339996687',
    projectId: 'admin-e5d62',
    storageBucket: 'admin-e5d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVmfOnJ-yhKl7rdcnT51ZuAkCfE7zI0A',
    appId: '1:588339996687:ios:6c0d86fe0ba6199a6a9b7a',
    messagingSenderId: '588339996687',
    projectId: 'admin-e5d62',
    storageBucket: 'admin-e5d62.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABhPR95yHorSq5cmo6yl4Yt3dnmjvPe48',
    appId: '1:588339996687:web:ac6bedd7860152666a9b7a',
    messagingSenderId: '588339996687',
    projectId: 'admin-e5d62',
    authDomain: 'admin-e5d62.firebaseapp.com',
    storageBucket: 'admin-e5d62.firebasestorage.app',
    measurementId: 'G-CSYF18GWYN',
  );
}
